name: Deploy on test server

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    env:
      DOTNET_INSTALL_DIR: "./.dotnet"

    steps:
      - uses: actions/checkout@v3

      - name: Configurando .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Instalando dependencias
        run: dotnet restore

      - name: Compilando
        run: dotnet build --configuration Release --no-restore

      - name: Publicando
        run: dotnet publish -c Release -o /var/www/sample-app

      - name: Recargando app
        run: |
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          systemctl --user restart sample-app.service
